<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>Libs\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\Images\**" />
    <EmbeddedResource Remove="Resources\Images\**" />
    <None Remove="Resources\Images\**" />
    <Page Remove="Resources\Images\**" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Resources\win.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="win.xaml">
      <Generator>MSBuild:Compile</Generator>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
    <Folder Include="Libs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="CustomTreeView\Style\BindableSelectedItemTreeViewStyle.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
    <Page Update="PathBar\Style\PathBarStyle.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
    <Page Update="PathBar\View\PathBarControl.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

</Project>
