//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppForLearning.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfAppForLearning.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentName_Control {
            get {
                return ResourceManager.GetString("ContentName_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CustomControl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentName_CustomControl {
            get {
                return ResourceManager.GetString("ContentName_CustomControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DragDropControl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentName_DroppableControl{
            get {
                return ResourceManager.GetString("ContentName_DroppableControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KeyboardNavigation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentName_KeyboardNavigation {
            get {
                return ResourceManager.GetString("ContentName_KeyboardNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProgressBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentName_ProgressBar {
            get {
                return ResourceManager.GetString("ContentName_ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserControl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContentName_UserControl {
            get {
                return ResourceManager.GetString("ContentName_UserControl", resourceCulture);
            }
        }
    }
}
